apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: unais-user
  POSTGRES_PASSWORD: secure-database
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: unais-non-root
  POSTGRES_NON_ROOT_PASSWORD: secure-non-root-user